version: "3.7"
services:
  mongo-service:
    image: mongo:5.0
    container_name: cognitive-exercises-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27117:27017"
  cognitive-exercises-memory:
    build: ./
    image: cognitive-exercises-memory:0.0.2-SNAPSHOT
    ports:
      - "8082:8082"
    depends_on:
      - mongo-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:password@mongo-service:27017
#      SPRING_RABBITMQ_HOST: rabbit-service
      GATEWAY-ADDRESS: http://localhost:9090
      KEYCLOAK_AUTH-SERVER-URL: http://host.docker.internal:8080/auth